### ISSUE TITLE
No EPG data available for RTS 1 HD nor RTS 2 HD

### ISSUE THREAD

**Issue by nbarrientos** [mathewmeconry/TV7_EPG_Parser#1]
Hi @mathewmeconry,

At least at the time of writing these lines there does not seem to be any EPG data in the full dump for these two channels. Haven't checked the other (smaller) dumps.

Tele.ch seems to have data, though. Perhaps there's some extra channel id mapping to do, I haven't checked the code in detail. Please let me know if I can help :)

![image](https://user-images.githubusercontent.com/131893/50057658-c59d6380-016d-11e9-83ad-a16f05213053.png)

**Comment by mathewmeconry** [comment]
Hi @nbarrientos 

Thanks for the information about these two channels.
I added the support to gather the channel info from both sources.

I'll close the issue when the data update is finished and I verified the output.

**Comment by mathewmeconry** [comment]
The dump is now up to date and rts1 and 2 are also included :)

**Comment by nbarrientos** [comment]
It works beautifully, thanks @mathewmeconry! Please ping me next time you're in Geneva, I'll be happy to buy you a beer :beer: :smile: 

![image](https://user-images.githubusercontent.com/131893/50071316-a59f8b80-01d1-11e9-9214-6012386c0061.png)

**Comment by mathewmeconry** [comment]
No problem :)
I'll keep your offer in mind. Thanks 😄
