### ISSUE TITLE
Earlier start time

### ISSUE THREAD

**Issue by m-a-v** [mathewmeconry/TV7_EPG_Parser#17]
The start time should be selected so that the running programs are also included. One possibility would be to simply get the epg data from the started day completely.

**Comment by mathewmeconry** [comment]
This doesn't make sense to me because when I run the script I'll update it with the data from now.
Additionally I'll fix today the cron job which should run the update of the data daily at 00:00 UTC

**Comment by m-a-v** [comment]
If you create it in the night it's not a problem, but if you create it on the fly then you will have no epg data for the current tv broadcasts. Probably, this is was a problem because of issue #15. I will check if this still happens with your fixes ;-).

**Comment by m-a-v** [comment]
This was also a problem because of issue #15. Already started broadcasts are also in the EPG.
